controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
api_exchange_rates:
  path: /api/exchange-rates
  controller: App\Controller\ExchangeRateController::index
  methods: GET
