parameters:
    open_exchange_rates_api_key: '%env(OPEN_EXCHANGE_RATES_API_KEY)%'

services:
    App\Command\RedisClientInterface: '@App\Command\RedisClient'
    App\Command\RedisClient:
        arguments:
            - '@predis.client'
    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'
    Predis\Client: ~
    GuzzleHttp\Client:
        arguments:
            - { base_uri: 'https://api.openrates.io/' } 
    # Default configuration for services in *this* file
    App\Command\CurrencyRatesCommand:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@GuzzleHttp\Client'
            - '@predis.client'
    
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Makes classes in src/ available to be used as services
    # This creates a service per class with the id being the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Add more service definitions when explicit configuration is needed
    # Please note that last definitions always *replace* previous ones
